### ISSUE TITLE
Prevent Redirect to YouTube and Capture Suggested Video URL

### ISSUE THREAD

**Issue by tusharhatwar1997** [PierfrancescoSoffritti/android-youtube-player#1189]
When the video is about to end, YouTube shows a suggestion for related videos. If the user clicks on a suggested video, the app is redirected to YouTube's official app or website, which I don't want.

I would like to:

Stop the redirect: Prevent the app from opening YouTube when a user clicks on a suggested video.
Capture the URL or video ID of the suggested video, so I can play it in the app's YouTube player instead of redirecting to the YouTube app or website.

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately YouTube's IFrame Player does not allow this.

**Comment by tusharhatwar1997** [comment]
Is there any workaround? This behavior is problematic as it keeps redirecting to YouTube every time.

**Comment by PierfrancescoSoffritti** [comment]
You could wait for the video to end and add an overlay on the player to intercept clicks. But it's a bit hacky. 

I had this same concern in my app a while back, and ended up deciding that it's not worth the effort to implement a workaround, since everything felt very hacky.

But let us know if you find a solution!
