### ISSUE TITLE
how do we get listener on video end?

### ISSUE THREAD

**Issue by navneetjain01** [PierfrancescoSoffritti/Android-YouTube-Player#123]

**Comment by Trusted97** [comment]
To do that you need to add a YouTubePlayerListener to your YouTubePlayer and, in its onStateChange method, listen for PlayerConstants.PlayerState.ENDED

**Comment by PierfrancescoSoffritti** [comment]
Hi, as @Trusted97 said, in order to listen for video-end events you need to add a `YouTubePlayerLister` to your `YouTubePlayer` and, in the `onStateChanged` callback, listen for the `ENDED` event.

```
youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
  @Override
  public void onReady() { // ... };

  @Override
  public void onStateChange(int state) {
    if(state == PlayerConstants.PlayerState.ENDED) {
      // video ended
    }
  }
});
```

You can read more [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/YouTubePlayer#events).

**Comment by navneetjain01** [comment]
thanks, it works for me.
