### ISSUE TITLE
saveInstanceState implementation

### ISSUE THREAD

**Issue by quendo1997** [PierfrancescoSoffritti/Android-YouTube-Player#139]
Could you make your youtubeView class save its current state by calling onSaveInstanceState? 

Everytime I rotate my screen the video-images are re-loading.

**Comment by PierfrancescoSoffritti** [comment]
Hi, 99% of the times you're using a YouTube player you also need to manually handle orientation changes (`android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout"`), otherwise when the user rotates its device all the data (video + images) that has been downloaded is lost. Resulting in a bad experience, where the app is potentially slowed down and used more data and battery than necessary.
Therefore, my general suggestion is to manually handle orientation changes.

Let me know if you think this solution doesn't apply to your app.

**Comment by quendo1997** [comment]
I would not call this (android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout") manually handeling the orientation changes. That makes android skip onCreate and onDestroy for that activity. For more information on this (https://developer.android.com/guide/components/activities/activity-lifecycle). It just rescales the screen contents and reuses the exsiting views. That does work, when you dont have a differing landcape layout. Incase you want to use a custom landcape layout you should implement the onSaveInstanceState method to secure the important data.

**Comment by PierfrancescoSoffritti** [comment]
That's precisely why it's referred to as "[manually handling orientation changes](https://developer.android.com/guide/topics/resources/runtime-changes#HandlingTheChange)", when the orientation changes the Activity is not destroyed and its up to the developer to adjust its content.

You can change the layout manually starting from the `onConfigurationChanged` method.

**Comment by quendo1997** [comment]
well okay. I dont want to "make it much more difficult" so yeah. If you dont want to implement it I will fork your libarry and implement it myself. Thanks for your help. All in all I really like your work!

**Comment by PierfrancescoSoffritti** [comment]
That's typically what you have to do though, when you have video players playing videos from the internet.

In any case, the library doesn't handle thumbnails, those are internal to the IFrame API.

If you only care about the images and you're ok with re starting the download of the video from 0 each time the orientation changes, you could implement a solution similar to the one suggested [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/issues/135).

Let me know if you find a better solution.
