### ISSUE TITLE
Video Rebuffering on orientation change and playing in 16:9

### ISSUE THREAD

**Issue by hacha0929** [PierfrancescoSoffritti/android-youtube-player#156]
As i requested orientation change my activity is recreated and again the buffering of the video takes place, if i use youtubeplayerview.engerfullscreen in my code then it enters full screen but in potrait mode only.

I want video in landscape mode without loosing the buffering.
https://drive.google.com/file/d/0B_F1L93eAIB6cVhfTUdOSVptUTFVTkZXeXZmdzZnTk55dGlr/view?usp=sharing
![screenshot 6](https://user-images.githubusercontent.com/40868193/42339341-55d89cf2-80aa-11e8-843a-97ce784e9737.png)

**Comment by PierfrancescoSoffritti** [comment]
Hi, the library is not responsible for changing the orientation of your app, that should be done in your app.

The video is re buffered because when the orientation changes the Activity is recreated. 
You should add this to the activity element in your manifest: `android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout"` to manually handle orientation changes. As @ambiguous1991 suggested you can refer to the other issue for more information.

Let us know if you need help.

**Comment by PierfrancescoSoffritti** [comment]
[Documentation](https://github.com/PierfrancescoSoffritti/android-youtube-player#full-screen) updated.

**Comment by hacha0929** [comment]
I added the following code to the manifest file,but now my video goes in
the full screen and comes back again.
below i share the screen recording of the application.

**Comment by PierfrancescoSoffritti** [comment]
I suggest you read [this page](https://developer.android.com/guide/topics/resources/runtime-changes) from the Android doc.

**Comment by hacha0929** [comment]
https://drive.google.com/file/d/1y_DhLwFsquRBqU7Pm64i2cSeftdpPlG_/view?usp=sharing

**Comment by PierfrancescoSoffritti** [comment]
It looks like you're changing the orientation programmatically to landscape but the physical orientation is still portrait.

This problem is Android-related, it's not due to the library.

**Comment by hacha0929** [comment]
okay, i removed the code of set requested orientation portrait but now this happens 
please help
https://drive.google.com/file/d/1W2TVXEdFZnr4SYQPpTKDUWASlYckf9Db/view?usp=sharing

**Comment by PierfrancescoSoffritti** [comment]
this is the same problem you had at the beginning, right? you need to [manually handle orientation changes](https://developer.android.com/guide/topics/resources/runtime-changes).
