### ISSUE TITLE
TransactionTooLargeException when loading Video

### ISSUE THREAD

**Issue by sunnahTv** [PierfrancescoSoffritti/android-youtube-player#197]
Hello,

when trying to play a video, an TransactionTooLargeException occurs..It seems that your library is serializing any Bitmap which is too large...see log:

```
D/Bitmap: **Bitmap_writeToParcel: Serialized SkColorSpace is larger than expected: 2016 bytes**
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3470356)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: blackstone.software.siratussunnah, PID: 11268
    java.lang.RuntimeException: android.os.TransactionTooLargeException: **data parcel size 3470356 bytes**
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4006)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.os.TransactionTooLargeException: data parcel size 3470356 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:748)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4636)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3998)
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

```
How to solve?

here is the code that I am Executing in my Actitivity:
```
        //set Player UI
//        val playerUIController = youtube_player_view.playerUIController
//        playerUIController.showYouTubeButton(false)
//        playerUIController.showFullscreenButton(false)

        lifecycle.addObserver(youtube_player_view);

        //Initialize PLayer
        youtube_player_view.initialize(YouTubePlayerInitListener {
            it.addListener(object : AbstractYouTubePlayerListener(){
                override fun onReady() {
                    it.loadVideo(videoId, 0f) //videoID, start at second
                }
            })
        }, true)

    }

    override fun onDestroy() {
        super.onDestroy()
        youtube_player_view.release()
    }

```

**Comment by PierfrancescoSoffritti** [comment]
Hi, how do you know the exception is related to the library?

**Comment by GregoryIwanek** [comment]
Hi. Same error, but since many **months** in my work project.

This error is most likely device wise, not library wise.

We didn't suspect library *could be* source of it, and found that it is a case just by accident ( one of new workers have device which potentially can produce this error). We had pretty heavy data use in a specific section of our app and we were looking in a wrong place as we thought it was related to something completely different.

Device model on which we were able confirm it was xiaomi redmi note 5 and HUAWEI P9 lite. Sometimes it happens on other models as well, but Huawei and xiaomi are responsible for ~80% of our error cases.

Error happens when this method is called. I wasn't able to reproduce it on debug builds ( can be because on debug/develop server we don't have that much data in previous screens, not like on production/release/store server, so more space is left for parcel on device to load data).
`public interface YouTubePlayer {
    void loadVideo(String var1, float var2);
...}`

From crashlitycs:
`Caused by android.os.TransactionTooLargeException
data parcel size 1298900 bytes`
 and + general non-specific stack of data ( in this error you don't get where exactly it does happen through crashlitycs)
`android.os.BinderProxy.transactNative (Binder.java)
  | android.os.Looper.loop (Looper.java:156)
  | android.app.ActivityThread.main (ActivityThread.java:6523)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)
`
Last thing I want to mention is that it crashed on our side in onResume(). I didn't check if it can crash if you call start of video from a button, so after completed onResume(), but it's really problematic to reproduce that. Just in case.
`    @Override
    protected void onResume() {
        super.onResume();
        if (youTubePlayer != null && currentSec != 0) {
            youTubePlayer.loadVideo(videoId, currentSec);
        }
    }`

Hope it will help.

**Comment by GregoryIwanek** [comment]
Just as I said it's from fabric.io and this particular error doesn't produce specific log info.

From user side: while opening some videos, start of new activity with player and then crash of an app.

From my side, my last resort while trying to find bugs: Since I located action of opening video as source of an error and can't debug, I've put dozens of 
`private String log = "" // variable, add calls of methods to produce pseudo-stack`

`public void someMethodInVideoActivity() {`
`log += "someMethodInVideoActivity or any text to print "`
`Crashlitycs.setString("log", log)`
`}
`

This way we can get pseudo stack of methods called, without debugging in fabric.io. Of course it's very simplistic and only on your activity level ( or better to say on the level of what you put there), but better than nothing.

In my case result of start new video activity and crash was:

Key | Value
Log | 
onCreate 
butterKnife // still in onCreate 
getIntent.videoId // get video id from intent, still in onCreate 
checkForSavedState // still in onCreate 
youTubePlayerView.initialize() // set listeners, still in onCreate 
fullScreenLis // add full screen listener, still in onCreate 

and last one
onResume

where this is called, the only method
`if (youTubePlayer != null && currentSec != 0) {
            youTubePlayer.loadVideo(videoId, currentSec);
        }`

**Comment by PierfrancescoSoffritti** [comment]
mmm ok. Still not sure if this error is caused by the library. Let me know if you learn something new!

**Comment by GregoryIwanek** [comment]
I guess then solution is to put couple of try-catch and retry to load video with some count of tries, and then if limit of tries set by me is meet say "sorry, video is not for you bro";).
https://stackoverflow.com/questions/36419493/getting-a-lot-of-crashes-from-android-youtube-player-api
Haha, I  see you at the bottom;].

This error didn't happen all time on these devices, I'd say it was 1/5 times, so I might try to use that approach. It's better to not show anything on screen, or try few times in quick session, than crash an app which is worst case scenerio in my ever.
