### ISSUE TITLE
How to hide "more videos" row when video paused?

### ISSUE THREAD

**Issue by mankidal19** [PierfrancescoSoffritti/android-youtube-player#226]
Hi it's me again. First of all, thank you very much for creating this library it is really helpful for my current project! 

However, I got some question, as mentioned above. I'm using your library to develop a TV app and currently as I pause the video, this "more videos" row will appear (as shown in picture below). Is it possible to make it hidden?

As far as I remembered, this row is not visible at some points of my development progress. I didn't exactly know what triggers it and how to make it hidden back.

[![IMG-20181019-151003.jpg](https://i.postimg.cc/1zBcrJ8Y/IMG-20181019-151003.jpg)](https://postimg.cc/066w8Gdp)

**Comment by PierfrancescoSoffritti** [comment]
Hi, I have noticed the same problem.
This library is built on top of the web version of the YouTube player. It seems that the team at YouTube is making some changes to the player. 

My current assumption is that you haven't done anything to trigger the bar, it is there because a different version of the player gets delivered.

There are two possible cases:
1. my assumption is correct: there is not much we can do about it. Unfortunately this changes are not reported in the player's documentation.
2. my assumption is not correct: it would be worth investigating why the web player is not behaving in a deterministic way. Maybe there is a problem with the `hide ui` flag.

**Comment by mankidal19** [comment]
I see. No wonder I think I only started to see this change lately. Actually I got a hunch similar as your assumption, and just to make sure I ask about it here.

Anyway, thanks a lot for the fast feedback!  Really appreciate it. :+1:

**Comment by PierfrancescoSoffritti** [comment]
I have looked at the update notes of the IFrame API, as expected they made changes to the player :/
can't say I'm happy about this.
https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018

**Comment by harrop99** [comment]
Thanks for your hard work on this.

**Comment by PierfrancescoSoffritti** [comment]
@ghozien unfortunately you cannot. The IFrame player doesn't allow it.

**Comment by ghozien** [comment]
because I will upload my application in the play store, and I don't want my application blocked by the play store because there is a YouTube logo.

**Comment by PierfrancescoSoffritti** [comment]
@ghozien this is not related to this issue. Open a new one or search for old issue related to this topic.

**Comment by HDharmesh** [comment]
> Yep, `rel = 0` behaves differently now.

can you help me 
how to use rel parameter ?

**Comment by PierfrancescoSoffritti** [comment]
You can use [IFramePlayerOptions](https://github.com/PierfrancescoSoffritti/android-youtube-player#iframeplayeroptions) to change its value.

**Comment by PierfrancescoSoffritti** [comment]
The change to the IFrame API seems permanent and there is no way around it, without using hacks. Therefore I'm closing this issue.

Buy using `IFramePlayerOptions` is possible to set the recommended videos to come from a single channel instead of from all of YouTube.
