### ISSUE TITLE
Load thumbnail only without playing video

### ISSUE THREAD

**Issue by jboxx** [PierfrancescoSoffritti/android-youtube-player#271]
Hi Pier,

Thanks to makes this wonderful library!
However, I want to ask how can I load thumbnail without playing video?
Yes, I know I can use `cueVideo` but it doesn't enough for my case.
I want to combine youtube official library with yours since their thumbnailing not be so good.
```
initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
    @Override
    public void onReady() {
        // I need load thumbnail only here
        initializedYouTubePlayer.cueVideo(carouselItem.getVideoId(), 0.0f);
        // I set onClick on YoutubePlayerView
        youtubePlayerView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // If Youtube playback doesn't available in the devices will play video 
                if (isYouTubeApiServiceAvailable != YouTubeInitializationResult.SUCCESS) {
                    initializedYouTubePlayer.play();
                } else {
                    // will play video using official library
                    initializedYouTubePlayer.pause();
                    YoutubeFullscreenPlayerActivity.launch(context, carouselItem.getVideoId());
                }
            }
        });
    }
});
```
Can I suggest to make another function to load thumbnail only?

**Comment by PierfrancescoSoffritti** [comment]
Hi, in order to load thumbnails you need to use the YouTubeData API. You can easily download a video's thumbnail from its id.

I don't intend to include the YouTubeData API as part of the core library, because it doesn't have anything to do with playing YouTube videos (the problem that this library is trying to solve).

I may create and extension/separate library for that in the future. For now I suggest to do it yourself, is going to be much faster :)
