### ISSUE TITLE
Read me google play buttons load invalid Google Play page

### ISSUE THREAD

**Issue by joejensen8** [PierfrancescoSoffritti/android-youtube-player#313]
Probably due to the changing of sample app package name, the read me does not open a valid page for the sample app

**Comment by PierfrancescoSoffritti** [comment]
Hey, thanks! I'm aware of the issue. Google decided that the name of the app was misleading and suspended it for impersonation. I'm trying to get it un-suspended by explaining that association with YouTube (the company) was never implied 😞. 

**For future readers:** the sample app has not been suspended because of the library, but because of the name it has on the PlayStore. The library itself doesn't break any policy or terms of service. Apparently it's just hard to publish a sample app for a YouTube player without them assuming that you're trying to impersonate YouTube 😅
