### ISSUE TITLE
issue with instant apps when initializing with  handleNetworkEvents=true

### ISSUE THREAD

**Issue by beyondeye** [PierfrancescoSoffritti/android-youtube-player#321]
When using androidyoutubeplayer in instant apps (tested on android 8.0), connectivity change events are not received and basically when setting handleNetworksEvents to true when initializing the AndroidYoutubePlayerView  does not work.
This is apparently because the android.net.conn.CONNECTIVITY_CHANGE event is not sent from the system with the flag FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS set.
see [here](https://medium.com/@erpragatisingh/instant-app-broadcasts-ff9b9ec16dcc)
and also a similar issues documented for another project [here](https://github.com/Adobe-Marketing-Cloud/mobile-services/issues/305)

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you for reporting the bug! I have never tested the library on instant apps. Do you have any suggestion for how to fix the issue?

I would assume the problem is related to `ConnectivityManager.CONNECTIVITY_ACTION` being deprecated. Even though I remember reading that the only problem should be that an broadcast receiver registered with `CONNECTIVITY_ACTION` is not going to work when the app is in the background (which is not an issue for this library). 
Maybe replacing the deprecated `CONNECTIVITY_ACTION` broadcast receiver with the new proper way of receiving network events can solve this problem?
I'm just talking of the top of my head, the problem may be elsewhere.

**Comment by beyondeye** [comment]
Hi, I don't know if the issue is with ConnectivityManager.CONNECTIVITY_ACTION being deprecated, but probably not. I think that the issue is related to the fact that in instant apps there are some additional constraints about what an app can do. Specifically to Broadcasts, only broadcasts sent with the flag FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS set can be received by an instant app, for the full list see (https://medium.com/@erpragatisingh/instant-app-broadcasts-ff9b9ec16dcc) (although I am not 100% sure it is complete). I don't really know what a possible solution can be. For now I am just using your (nice) library with handleNetworksEvents disabled

**Comment by PierfrancescoSoffritti** [comment]
I'll look into it next time I have a few spare hours. If you manage to find a solution feel free to send a pull request.

**Comment by beyondeye** [comment]
sure, thanks a lot
