### ISSUE TITLE
Question regarding playback count

### ISSUE THREAD

**Issue by eneim** [PierfrancescoSoffritti/android-youtube-player#338]
Thanks for the lib.

I have a long time struggling with YouTube playback. One of my concern is that using a 3rd-party library is safe for content creator or not, regarding the revenue from playback view.

In [this doc](https://developers.google.com/youtube/iframe_api_reference#playVideo), it says

```
Note: A playback only counts toward a video's official view count if it is initiated via a native play button in the player.
```

Do you have any detail about this. I know that if we use WebUI, and let user click to the button rather than start it automatically (by loadVideo), it will be fine. I wonder if a general auto load/play will be fine or not.

**Comment by PierfrancescoSoffritti** [comment]
Hey, from what the doc is saying it seems like you should not use `loadVideo` if you want the view to be counted. It may be worth testing though. You could upload a video on your YouTube channel and play it a few times using `loadVideo`. Let me know if you do it. Otherwise I'll do it myself, not before next week though.

**Comment by eneim** [comment]
@PierfrancescoSoffritti Have no idea but it seems that calling "loadVideo" *does* count to the view count. It sounds good, but as the doc says, I will try to take a further look.

**Comment by PierfrancescoSoffritti** [comment]
ah, interesting. Keep me updated if you find something!
