### ISSUE TITLE
Provide an option to play by URL instead of by ID

### ISSUE THREAD

**Issue by JohannesPertl** [PierfrancescoSoffritti/android-youtube-player#540]
It would be easier to use to just provide a direct Youtube URL

**Comment by PierfrancescoSoffritti** [comment]
Why? the video id is in the URL.

**Comment by JohannesPertl** [comment]
Yes, it may be trivial, but also more convenient to use. Instead of having to extract the id with regex, that functionality could be provided directly by the library

**Comment by juanmendez** [comment]
I hope this helps https://regexr.com/566ho

**Comment by Faravy** [comment]
> Why? the video id is in the URL.

I have to play the live video in which the URL is almost fixed (ex: https://www.youtube.com/c/news24tv/live), and there is no video id in that URL, so how can I play that?

**Comment by malliaridis** [comment]
The probably easiest and most error free way is to convert a URL string to a URI object and read the video id with predefined methods. This would look like below:
```java 
String urlString = "https://www.youtube.com/watch?v=F-xysz1wNbo&ab_channel=SoundCloudx";
Uri uri = Uri.parse(urlString);
String videoId = uri.getQueryParameter("v");
```
I think it's better if the library requires only the video ID and does not support URLs, because YouTube might change the URL format or provide various other formats of URLs or URIs (next to the share URL that looks like https://youtu.be/F-xysz1wNbo) which might crash the apps or make the library not functional in the future. By requiring the video ID you always have a common entry point regardless the format of the URI. 

@Faravy It seems that the live stream support is not working at all (I guess the iFrame API from YouTube does not allow that). This URL format however would not work, even if live streams would work properly. You should use the video ID that is provided in the URL of the share url of the live stream / video (in your case `L9So8AmTr1k`).

I think this ticket can be closed for now. Maybe in the future if this will be a more popular request we can discuss again. :)

**Comment by juanmendez** [comment]
@malliaridis I like your approach finding the `v` param. Maybe there is more information regarding finding the first segment from`http://youtu.be/NLqAF9hrVbY`, that's part of why I shared that regex.

**Comment by malliaridis** [comment]
@juanmendez it's as simple as
```java
Uri uri = Uri.parse("http://youtu.be/some-id");
String path = uri.getPath(); // result to "/some-id"
// or if it contains multiple segments seperated by "/"
List<Strging> segments = uri.getPathSegments();
// uri.getPathSegments().get(0) results to "some-id"
```
I hope I understood your question correctly. :)

**Comment by juanmendez** [comment]
@malliaridis yes, that's what I meant. That's awesome!

**Comment by PierfrancescoSoffritti** [comment]
@Faravy live video support was working last time i checked (it was a while ago). But you probably need to use the YouTube Data API to get the video ID.
