### ISSUE TITLE
Infinite loading on Android 4.4 with library version 2.x

### ISSUE THREAD

**Issue by talklittle** [PierfrancescoSoffritti/Android-YouTube-Player#59]
Try running sample app on Android 4.4 emulator. It shows as loading infinitely.

Seems to affect library version 2.0.0 and 2.1.0.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I have never managed to get the library working on emulators, I think there's some problem with the version of WebView installed on emulators. Was it working for you using older versions of the library?

You could try to investigate if the method `onYouTubeIframeAPIReady` is called, in youtube_player.html.

In general there may be some inconsistencies with Android 4.4, even on physical devices, since WebView is not update through the store, as it is starting from Lollipop.
For example the player wasn't working on a CyanogenMod 4.4 I had installed on a Samsung Galaxy s2, but it was working fine with CyanogenMod 4.4 on a Galaxy Nexus.

Maybe it wouldn't be a bad idea to increase the minSdk for the library and stop supporting KitKat.
