### ISSUE TITLE
Make it easier to switch from the official YouTube library

### ISSUE THREAD

**Issue by Glurt** [PierfrancescoSoffritti/Android-YouTube-Player#6]
I've come across this library midway through developing my app with the official library, now that I want to switch to this library I'm finding it a bit of a pain since a lot of things are different. 

Firstly, can we split the **YouTubeListener** interface up a bit to match the official library as much as possible, it should make it easier to listen for callbacks on the methods you actually want and get rid of the need of **AbstractYouTubeListener**.

Which leads me onto my next issue, when I call initialize() I want to know whether it succeeded or failed, I know there's the call to _onPlayerReady()_ but what happens if I decide I don't want the library to handle network changes and the device isn't connected to the internet? If there was an **OnInitializedListener** that had methods like _onInitialiseSuccess()_ and _onInitialiseFailed()_ then it would make it easier to know what has happened. 

Lastly, I'm using MVP in my app which means I need to keep android dependencies out of my Presenter. If I want my Presenter to control the player then my Activity/Fragment needs to match each method on the player load/cue/play/pause etc which seems a bit pointless. It would be better if the onInitialiseSuccess method returned an interface called **IYouTubePlayer** containing all of the methods the **YouTubePlayer** implements. That way the Presenter can keep a reference to **IYouTubePlayer** and control it directly.

I'm willing to do this work myself but I wanted to see if you thought it was good idea before I submit a PR. Let me know what you think.

**Comment by PierfrancescoSoffritti** [comment]
Hi!
1. Switching from the official library to this one should not be super hard.I've had both of them in my app for a while, interchangeable from a preference. The use of two adapters (eg. NativeYouTubeAdapater and WebYouTubeAdapter) may be the solution.
How do you suggest to split the YouTubeListener?

2. I agree, the current implementation is not very elegant. What I thought at the time is that a Network Receiver must be there in a way or the other. Even if you use your own network receiver (which is preferable) you must call the methods onNetworkAvailable/Unavailable every time the connection changes. All this obviously isn't enforced in any way, which is bad.
Don't you think that the addition of a OnInitializedListener would be misleading? and maybe unnecessary, considering that the library already knows how to handle initialization failures? wouldn't it better to enforce the use of a network receiver when handleNetworkEvents is false?

3. I think the idea is good, I am also using MVP in my app and I've done something similar. But I don't think this behaviour should be implemented in the library. It may be useful in a MVP context, but doesn't make much sense otherwise. After all the YouTubePlayerView is just a View, why a View should return an interface to its methods?
Instead you could create a PlayerController and give it a reference to the YouTubePlayerView, then pass the PlayerController to your presenter. In my app I've done it a little bit different, I've created a presenter only for the YouTubePlayerView, which sees only a VideoPlayerInterface, that has the common playback commands.

Obviously those are just some issues I've seen, but I may be wrong. After all I've implemented the library in a rush, because my neo released app was crashing and i had to replace the YouTubePlayer ASAP. So the design may not be the best possible :)

let me know what you think! and thanks for the help/interest in the lib!!

**Comment by Glurt** [comment]
I've created a gist as to how I think the listener could be split up into separate groups of related callbacks, this would require changing the player.html and the YouTubeBridge but I think it would provide better information to the developer using the library. I've also put the listeners in an interface which is one of the points I'll go into.

Here's the gist https://gist.github.com/Glurt/01970f074db82c8a256bf0198173230a

1. I can see your point, if the player knows how to handle network errors then why give a callback? But what happens if there is any other type of error, I know that the player itself will call onError but what about if the WebView's onReceivedError is called? You know this better than I do so there might not be any reason to handle this but if an error occurs that the library can't handle itself then I'd like to know about it. 

2. My suggestion for using an interface to control the player comes from the official library itself, when you call initialise on the YouTubePlayerView it gives you back an [interface](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer) which you use to control the player itself without going through the view. Personally this makes more sense to me because it means the YouTubeView is responsible for showing the Player and controlling the layout whilst the Player is responsible for the actual playback functionality. Admittedly, if you aren't using MVP then you won't see a huge gain from this but if you are then it reduces the number of calls from:
Presenter > View > YouTubePlayerView > YouTubePlayer
To:
Presenter > YouTubePlayer

Overall I like what you've done, it works much better than the official library but I think a little bit of cleanup could make it even better. There's a couple of other minor points I'd like to change as well but we can discuss this during the PR if you're happy for me to make any changes.

**Comment by PierfrancescoSoffritti** [comment]
Ok, you've made some good points. I'm currently super busy studying for an interview (with Google :|), it'll be in a couple of days from now.
After the interview I'll be able to look through the code and suggestions you've made with more attention! (btw I had a look at the interfaces and I like where this is going)

I'll get back to you in 2/3 days :)

**Comment by Glurt** [comment]
That's like my dream job, good luck dude!

**Comment by PierfrancescoSoffritti** [comment]
1. I'm looking at the gist.  
 - Why there's a `interface OnFullscreenListener`?
 - `interface PlaybackEventListener` this should really be called `PlaybackStateListener`, the library should be as similar as possible to the [IFrame API](https://developers.google.com/youtube/iframe_api_reference#Playback_status)
 - Where would you pass in the` PlaybackEventListener` and the `OnFullscreenListener`? In the initialize method? Looks good to me. But what about the other methods? :) (eg. onCurrentSecond, onVideoDuration etc)

2. I think the only thing that may go wrong during initialization is not being able to download the YouTube library from the web. No other errors should occur at this point. Therefore there's no need of a listener. The player has to be re initialized when the network is available again. I'll see if I can improve this part of the library, it's not very pretty at the moment.

3. Ok, looks good to me! This approach will also help us remove some duplicate methods in the YouTubePlayerView. But a new problem is introduced: with the current implementation is easy to sync the UI with the YouTubePlayer, how would you do that using the interface? (eg. `cueVideo()` of the YouTubePlayerView calls `youTubePlayer.cueVideo(videoId, startSeconds); playerControlsWrapper.onNewVideo();`. This may be useful in other situations.)

**Comment by Glurt** [comment]
1) The gist was thrown together rather quickly so it's not quite perfect.

- The OnFullscreenListener is there to let you know the player is entering/exiting fullscreen, chances are you won't need it but some people might need to do something when fullscreen is triggered. 
- That's fine with me, it was just a name I made up anyway.
- I forgot to add methods for adding and removing listeners to the interface so they would be accessible at any time. I've actually started refactoring the forked version and realised that onCurrentSecond is necessary so that can be added back. I've also altered the playing callback to be _playing(final String videoTitle, final String videoId, final float videoDuration);_.

2) That sounds fine to me, I wasn't too sure so I thought it best to ask you.
3) I'm starting to wonder why the YouTubePlayerView exists in the first place, could you not treat the WebView as the view and have it contain a reference to the PlayerControlsWrapper? 

I'm doing some heavy refactoring at the moment to see what works so I'll push everything to my forked version and let you take a look.
