### ISSUE TITLE
How to start the YoutubePlayerView without being on a buffering state.

### ISSUE THREAD

**Issue by fmiguelmmartins** [PierfrancescoSoffritti/android-youtube-player#638]
Hi mate,

Great framework and wonderful idea. The official library really sucks so thanks for taking the time and effort to give this to the community.

I have a very simple question, I would like to add the player to my application but without any video being passed onto to it. So, for example, at the moment I have the following xml in my frament:

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        tools:background="@color/black"
        tools:context=".fragments.mainfragments.YoutubeFragment">

    <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:autoPlay="false"/>


</RelativeLayout>
```

The problem is, in my fragment I have the following appearing:

<img width="210" alt="Screenshot 2020-10-01 152857" src="https://user-images.githubusercontent.com/25081580/94822749-e98d7000-03fa-11eb-88df-fe5d8269317b.png">

How can I get rid of that "Buffering" circle and have the player in a kind of "off" mode?

Also, in the emulator the videos are super slow and the whole app (because it's running in the UI thread) is mega slow. 

Many thanks in advance.

**Comment by malliaridis** [comment]
Normally you should be able to turn this off with the following lines of code: 
```java
YouTubePlayerView youTubePlayerView = findViewById(R.id.youtube_player_view);
youTubePlayerView.getPlayerUiController().showBufferingProgress(false);
```
However, the progress bar seems not to respond to this update, even if you do it after the player is ready. If this is not a bug, this is probably because the plalyer has not loaded any video yet and therefore hasn't changed his state to a state it updates the UI controller's elements. I would remove the view with the UI controller's `removeView` method, but that doesn't seem to work either.

**The solution** is probably, if you keep using the `DefaultPlayerUiController`, to get the view of the progress bar with `findViewById(R.id.progress)` and manually set it's visibility to `View.GONE` or `View.INVISIBLE`.

What you can do and might be what you actually want is to set up a custom `PlayerUiController`. This allows you to show something differently when no video is cued / loaded in the layout element and show only elements you want when a video is played. There is for this action some examples in the sample app. 

And last but not least, about the performance of your app in the emulator: have you enabled hardware acceleration on your development computer?

**Comment by fmiguelmmartins** [comment]
Thank you for taking the time answering my question mate. That helped a lot! Great tip regarding hardware acceleration. I did not have this feature enabled and it is working fine now!
