### ISSUE TITLE
App rejected by Device and Network Abuse

### ISSUE THREAD

**Issue by zeropol2** [PierfrancescoSoffritti/android-youtube-player#640]
Google Play gave me the screenshot.

![image](https://user-images.githubusercontent.com/4046250/95008001-c956ee80-0650-11eb-927f-004c745e92c6.png)

This is my settings.

```
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/playerView"
            android:layout_width="@dimen/playerSmallWidth"
            android:layout_height="wrap_content"
            android:layout_below="@id/playerActionBar"
            app:showFullScreenButton="true"
            app:showYouTubeButton="false" />
```

**Comment by malliaridis** [comment]
Does you app provide only youtube video playing functionality? Cause this is for sure an abuse.

@PierfrancescoSoffritti the rejection might affect other users too, but not because of the functionality of the app. Do you see the youtube icon which is outlined in the screens? This sometimes pop up on my instances too, and seems to be from the iFrame.
See for example this: ![youtube_elements_on_top](https://user-images.githubusercontent.com/33470669/95015859-b55ebd00-064f-11eb-870c-b9c1fb3d902c.png)

**Comment by PierfrancescoSoffritti** [comment]
Yes i am aware of this. I think the safest thing to do is to always use webUi instead of the native one i've built. With the native one YouTube might not be happy because we are covering part of the video/modifying behaviour of the player.

WebUi should be the default UI. A PR was merged a few months ago to make that change, but I never had time to polish things and publish a new version.

**Comment by malliaridis** [comment]
Just for reference: The PR #524.
Think this issue can be closed then.
