### ISSUE TITLE
Write change log

### ISSUE THREAD

**Issue by tellfa** [PierfrancescoSoffritti/Android-YouTube-Player#65]
Please write change logs of version 2 and  3

**Comment by PierfrancescoSoffritti** [comment]
I will start writing a change log from the next version. Not much is changed from 2 to 3. I have added a [menu ](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Menu) to the player and refactored some part of the library. I had to increase the major version because the refactoring introduced some breaking changes.
