### ISSUE TITLE
Seeking relative milliseconds 

### ISSUE THREAD

**Issue by pralgomathic** [PierfrancescoSoffritti/Android-YouTube-Player#80]
`public abstract void seekRelativeMillis (int milliSeconds)
`
Seeks forward or backward by the specified number of seconds.

milliSeconds | Number of milliseconds to seek forward, if positive, or backward, if negative.
-- | --

This method is presented in YouTube API, is it possible to get something like, with using this Player?

**Comment by PierfrancescoSoffritti** [comment]
Hi, [YouTubePlayer](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayer.java) already has "seekTo".
But yeah, seekRelative could be added.
If you want to do it feel free to send a pull request. Otherwise I can do it over the weekend!

**Comment by pralgomathic** [comment]
I've implemented `seekRelativeMillis` adding positive(to seek forward) or negative (to seek backward)  values with `onCurrentSecond`, is it necessary then to implement inside library ?

**Comment by PierfrancescoSoffritti** [comment]
Feel free to send me a pull request 👍

**Comment by thesultanster** [comment]
@PierfrancescoSoffritti is this enhancement in version 4.1.7? I cannot find it.

**Comment by PierfrancescoSoffritti** [comment]
Hi, no it is not. I don't want to clutter the API too much with noise, it s easy for library s users to build a method do to just that.

But,  I may release an helper for that in the next version.
