### ISSUE TITLE
Youtube Ads

### ISSUE THREAD

**Issue by bironader** [PierfrancescoSoffritti/Android-YouTube-Player#86]
I want to know if the player works like Youtube player API and its show Youtube ads?

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, the player works and is simpler to use than the YouTube player API. Also it's stable, the YouTube player API wasn't stable at all last time I used it.

For some reason the web based YouTube player doesn't play ads. Therefore no, this player doesn't play YouTube ads at the moment. That's beyond my control, since it's a limitation of the web based YouTube player.

**Comment by fouri** [comment]
> Hi, the player works and is simpler to use than the YouTube player API. Also it's stable, the YouTube player API wasn't stable at all last time I used it.
> 
> For some reason the web based YouTube player doesn't play ads. Therefore no, this player doesn't play YouTube ads at the moment. That's beyond my control, since it's a limitation of the web based YouTube player.

 I am planning to publish my app using this library. Can this be a reason for Play Store to reject the app?

**Comment by PierfrancescoSoffritti** [comment]
@fouri no, this is the default behaviour of the web player, therefore it is not an issue.

**Comment by fouri** [comment]
@PierfrancescoSoffritti I don't have `app:useWebUi=true` as a parameter and ads are not shown. So it also uses the web player, right?

**Comment by PierfrancescoSoffritti** [comment]
Yes, this player always uses the web player.
