### ISSUE TITLE
Replace http with https in DefaultPlayerUiController

### ISSUE THREAD

**Issue by ArcherEmiya05** [PierfrancescoSoffritti/android-youtube-player#860]
The library uses HTTP not HTTPS

![image](https://user-images.githubusercontent.com/38008900/173411593-3b231543-1f83-4048-ba91-c5bfea61f8a1.png)

**Comment by Serkali-sudo** [comment]
That is not really a security issue because:

1. That code is click listener of YouTube button that opens that video on YouTube app or web,And this button only exists on custom design and it doesn't matter because library is using webui as default.Heres original code : [DefaultPlayerUiController.kt#97](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/ui/DefaultPlayerUiController.kt#L97)
2. The library doesn't connect to that link to play video,It uses [IFrame Player API](https://developers.google.com/youtube/iframe_api_reference) which connects to `https://www.youtube.com/iframe_api`, Heres html page that player is loading : [ayp_youtube_player.html](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/res/raw/ayp_youtube_player.html#L20)
3. Most of phone has YouTube app installed so even this button sends you to http link it will open on youtube app by default anyways but lets say that phone doesnt have youtube app or it is not default, even then youtube itself will automatically redirect https version of site.

**Comment by PierfrancescoSoffritti** [comment]
I agree this is not a security issue. 

I'll rename the issue to keep it as a reminder to replace `http` with `https` in the next release.
Thanks @Serkali-sudo for taking a look :)
