### ISSUE TITLE
Playing of Youtube shorts

### ISSUE THREAD

**Issue by bryan-ibrahim** [PierfrancescoSoffritti/android-youtube-player#878]
# YouTube shorts

I tried loading a YouTube short video but seems like the lib still doesn't support it yet

--Result: this video could not be found

Could this feature please be looked into or added if possible

**Comment by PierfrancescoSoffritti** [comment]
I don't think the IFrame player supports shorts. There's not much we can do about it.

**Comment by bryan-ibrahim** [comment]
Ok noted

**Comment by Serkali-sudo** [comment]
IFrame player already supports YouTube shorts.
I think you probably entered video id wrong.
For example :
this is example shorts video link = https://www.youtube.com/shorts/RImXuH7GDig
As you see id part of this shorts is at the end of the link ,just after `shorts/` which is = RImXuH7GDig
when you play video with this id it should play the video.
Because shorts videos are not different than normal videos
For example if you put this shorts video id to normal YouTube video link it will open as a normal video:
https://www.youtube.com/watch?v=RImXuH7GDig
So i think you should check your shorts video id.

**Comment by PierfrancescoSoffritti** [comment]
ah cool, thanks @Serkali-sudo for correcting me :)
