### ISSUE TITLE
I received a policy violation from the Play Store

### ISSUE THREAD

**Issue by jmanchester68** [PierfrancescoSoffritti/android-youtube-player#883]
From what I can tell, the issue is the Share option under the three dot menu button. In order to get rid of that, the only thing I could figure out was to use the DefaultPlayerUiController. This got rid of the menu, but it also dropped a number of other controls, including the Closed Captioning button. I tried using the cc-load-policy to get captions to show by default, but that didn't work either. Does this look correct (Kotlin)? 

IFramePlayerOptions.Builder()
                    .controls(0)
                    .ccLoadPolicy(1)
                    .build()

Do you know of any other ways to get rid of the Share option in the menu, as an alternative? 

I attached a screenshot of the message I received from the Play Store, along with the image they sent showing the violation.
![org bridgelearning uscitizenshipprep-InAppExperience-48](https://user-images.githubusercontent.com/85249943/188979968-769615e9-206b-475d-9d94-5166ecc43e77.png)

![image](https://user-images.githubusercontent.com/85249943/188978517-5e9bb2f4-8c6e-46ff-9e93-9b83faee84ac.png)

**Comment by PierfrancescoSoffritti** [comment]
I don't think this is related to the "share" button. The player itself is definitely fine, as you are using webUi, which is exactly what Google provides.

What I suspect is that the app got rejected because of the ads you added to the screen. I suggest you read the YouTube Terms of Service to see if you can find something.

**Comment by PierfrancescoSoffritti** [comment]
It could also be that Google made a mistake in flagging your app. This is the last resort, carefully read the terms of service first.

**Comment by PierfrancescoSoffritti** [comment]
Let us know how the resubmission goes.

I would recommend using webUi ad avoiding customizing the UI, if you plan to publish on the PlayStore. As UI customization might break YouTube terms of service.

As per the subtitles, checkout the IFrame API documentation, maybe there is a way to enable them automatically.
In my experience, some of the methods they provide don't work on mobile, but it's been a while since I looked.

As per using Kotlin, everything should work fine, as Java and Kotlin are interoperable.

**Comment by jmanchester68** [comment]
Removing the banner ads resolved the issue. There is a cc-load-policy setting in the iFrame documentation, but it does not appear to work on mobile Android apps. Good to know that I wasn't missing something. Thanks for your responsiveness, I really appreciate the help!

**Comment by PierfrancescoSoffritti** [comment]
Nice, i'm glad it worked out :)
