### ISSUE TITLE
Workaround for hiding the channel watermark button at top of the fullscreen button

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#950]
First of all, thanks, @PierfrancescoSoffritti for this library and all your efforts.

# Question / Problem

### Summary

We do have a workaround for hiding the [annoying views](https://github.com/PierfrancescoSoffritti/android-youtube-player#remove-annoying-views) of Title and More Videos. But how to hide the channel watermark button (aka channel branding button) that appears on the top of the full-screen button? When we click this channel button, it redirects to the channel page on youtube. I want to hide this button or make it nonclickable. Can someone please guide how to implement this like the [other workarounds](https://github.com/PierfrancescoSoffritti/android-youtube-player#hide-title)?

**Comment by PierfrancescoSoffritti** [comment]
Can you add a screenshot of what you're referring to? @Serkali-sudo was the one implementing those solutions, maybe he has some ideas?

If not I suggest inspecting the html and finding the tags you want to remove.

Remember that doing this kind of modifications is not recommended. It might break YouTube terms of service.

**Comment by MananArya22** [comment]
<img width="306" alt="Screenshot 2023-03-31 at 10 00 04 PM" src="https://user-images.githubusercontent.com/17155215/229178161-050a5140-03e8-492e-afa0-67216b2bf56d.png">
@PierfrancescoSoffritti This is the button with the channel icon I am referring to and wish to remove.

**Comment by PierfrancescoSoffritti** [comment]
I see, I'll leave it to @Serkali-sudo , he knows more than me about this.

**Comment by Serkali-sudo** [comment]
You can delete or change any item on the player. Just find the necessary tag ,class or id by inspecting with the browser.

You can find element's properties with this demo iframe api site : https://developers.google.com/youtube/youtube_player_demo

That being said, to remove that image you can use something like this(since the image will be hidden it will be unclickable):

```js

function hideBranding() {
  const playerIFrame = document.querySelector("iframe");
    if (!playerIFrame) {
      return;
    }
    
    const frameDoc = playerIFrame.contentDocument;
    if (!frameDoc) {
      return;
    }

    const branding = frameDoc.querySelectorAll('.iv-branding')[0];
    if (branding) {
      branding.style.display = 'none';
    }
}
```
Call this code from onReady

So this code should remove that image but if it is showing again after an action put this code to a setInterval method

And Rememeber this kind of actions may break youtube terms of service.

**Comment by PierfrancescoSoffritti** [comment]
Thanks @Serkali-sudo!
