### ISSUE TITLE
How to make "More options" non clickable/disable it

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#960]
# Question / Problem

In the settings tab, there is a "More options" menu item below the "Quality" menu item, which further contains a lot of useless items. I want to make this "More options" menu item non-clickable. This is not visible in the youtube demo "https://developers.google.com/youtube/youtube_player_demo", but is visible in the demo app provided. @Serkali-sudo Can you please suggest how to make this non-clickable or hide it (In case it does not violate the youtube terms and conditions)?

### What I've tried
I tried searching for its HTML element but it is not visible in the demo video.

![WhatsApp Image 2023-04-08 at 11 36 15 AM](https://user-images.githubusercontent.com/17155215/230706297-d1aebabe-beec-4854-9598-f011c719e849.jpeg)
![WhatsApp Image 2023-04-08 at 11 36 04 AM](https://user-images.githubusercontent.com/17155215/230706299-2961124f-f43c-4e46-9842-4f55388c51c9.jpeg)

**Comment by PierfrancescoSoffritti** [comment]
> In case it does not violate the youtube terms and condition
It does violate them, you shouldn't do any modification on the player.

**Comment by MananArya22** [comment]
In that case, @Serkali-sudo Can you please suggest how to make this non-clickable?

**Comment by PierfrancescoSoffritti** [comment]
Technically, any modification is not allowed, as far as I know. But it's hard for them to enforce it. For example, Tumblr uses this library with the default custom UI, and they're fine.

**Comment by Serkali-sudo** [comment]
making an element non-clickable is still a modification.And if you are worried about breaking Youtube Terms of Services you shouldnt do that.

But if you want to do anyways and cant find element properties with the default version of the demo site then learn your test android device's user agent and open the demo site with that user agent.

If the demo site site doesnt work you can alternatively create a simple html page that loads a video with iframe player and then apply phone user agent

With these ways you should be able to see those options.Sorry i cant provide spesific code because i currently dont have a access to a PC.

**Comment by Serkali-sudo** [comment]
> Technically, any modification is not allowed, as far as I know. But it's hard for them to enforce it. For example, Tumblr uses this library with the default custom UI, and they're fine.

I agree because there is a app called [Cake](https://play.google.com/store/apps/details?id=me.mycake)

This app is has 100M+ and it teaches you english by watching youtube videos with subtitles and to play youtube video it opens youtube embed link inside a webview(it is pretty much doing the same thing with this library) and if you notice iframe api connects to embed link. i think you can say that this app using almost same method to play a youtube video like this library and they use webui and they hide every element on the screen except youtube logo on the right bottom.

So i think unless you dont hide youtube logo on the right bottom screen its fine to remove everything else this is what this app did and it seems to be fine after 100 million downloads.

But of course it is best to not to do any modification on the player.

**Comment by PierfrancescoSoffritti** [comment]
Cake has a pretty nice implementation of the player. Maybe we should add an example to the sample app that looks like their player.

**Comment by Kareem7assan** [comment]
i have the same issue i wondering if i can hide more options or make it non-clickable

**Comment by MananArya22** [comment]
> 
> But if you want to do anyways and cant find element properties with the default version of the demo site then learn your test android device's user agent and open the demo site with that user agent.
> 
> If the demo site site doesnt work you can alternatively create a simple html page that loads a video with iframe player and then apply phone user agent
> 

@Serkali-sudo The user agent of my device is: "Mozilla/5.0 (Linux; Android 13; LE2111 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36"

I tried creating an Iframe with this user agent: 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Embedded YouTube Video</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RJrNZ6TVssU?user_agent=Mozilla%2F5.0%20%28Linux%3B%20Android%2013%3B%20LE2111%20Build%2FTP1A.220905.001%3B%20wv%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Version%2F4.0%20Chrome%2F111.0.5563.116%20Mobile%20Safari%2F537.36" frameborder="0" allowfullscreen></iframe>
</body>
</html>

But, I still cannot see the "More options" menu item under the settings menu. Can you please suggest what to do?

**Comment by Serkali-sudo** [comment]
I meant view mobile version of the demo iframe site using chrome's inscepting feature.

Chrome has a little phone icon on the developer tools. use that to view it in mobile version and use iframe api you seem to used embed link.

Anyways i found the neccesary tag if you want heres basic code:

function hideMorePopup() {
    const playerIFrame = document.querySelector("iframe");
    if (!playerIFrame) {
      return;
    }
    
    const frameDoc = playerIFrame.contentDocument;
    if (!frameDoc) {
      return;
    }

const s_popup = frameDoc.querySelector(".ytp-settings-menu");

    const o_options = s_popup.querySelectorAll(".ytp-menuitem")[s_popup.querySelectorAll(".ytp-menuitem") - 1];
    if (o_options) {
      o_options.style.display = 'none';
    }
  
}
```

**Comment by MananArya22** [comment]
@Serkali-sudo Thanks for the guidance and for providing the necessary tags. The code you shared, deleted the last element irrespective of whether it is a "More options" menu item or not. I have used this code to hide it that checks whether it is "More options" menu item or not and deletes it only if it is.

`    function hideSettingsMoreOptions() {
      const playerIFrame = document.querySelector("iframe");
      if (!playerIFrame) {
        return;
      }

      const frameDoc = playerIFrame.contentDocument;
      if (!frameDoc) {
        return;
      }

      const s_popup = frameDoc.querySelector(".ytp-settings-menu");
      const moreOptionsItem = selectItem(s_popup, ".ytp-menuitem", "More options");

      if (moreOptionsItem) {
        moreOptionsItem.style.display = 'none';
      }
    }


    function selectItem(node, selector, text) {
      if (text) {
        const result = Array.from(node.querySelectorAll(selector))
                .find(item => item.innerText.includes(text));
        return result;
      } else {
        return node.querySelector(selector);
      }
    }

`

This works fine for me. @Serkali-sudo please review this one.

**Comment by Serkali-sudo** [comment]
@MananArya22 Your code looks more stable and better than mine but the only downside is that if they change the "More options" text a little bit this code wont hide the element. So you should create a different second method that you can call if this method fails.
Btw you dont need to check if text is null or not in "selectItem" function since there is no other possibility.

**Comment by MananArya22** [comment]
Sure, @Serkali-sudo. Thanks, @Serkali-sudo  and @PierfrancescoSoffritti!
